config/routes.rb
Scaffold::Application.routes.draw do
  namespace :front do
    get 'portal/index'
  end

  devise_for :users, skip: [:registrations], controllers: {sessions: 'common/sessions'}

  root 'portal#index'
  get 'shop' => 'front/homes#home'
  get 'admin' => 'admin/users#index'

  get 'free_express' => 'portal#free_express'
  get 'get_addr/:id' => 'portal#get_addr'
  get 'notice/:id' => 'portal#notice'
  post 'save_addr' => 'portal#save_addr'

  namespace :front do |front|
    namespace :homes do
      get :pay_view
      post :pay_call_back
      get :express
      get :home_index, format: 'json'
      get :get_classification
      get :get_shop
      get :get_region_shop
      get :shipping_address
      get :shipping_address_default
      get :get_order_old
      get :get_order_ing
      get :get_order_detail
      get :get_score_detail
      get :get_person_info
      post :commentary_order
      post :shipping_address_change
      post :shipping_address_new
      post :order_new
      get :cancel_order_customer
      post :express_entrue
      post :pay_online
      post :change_person_info
      post :search_shipping_info
    end
    resources :contacts do
      collection do
        get :upload
        post :upload_file
        get :tree_data, format: 'json'
      end
    end

    get 'users/edit' => 'users#edit'
    patch 'users/update' => 'users#update'
    get 'users/update_password' => 'users#update_password'
    patch 'users/update_password' => 'users#update_password'
    resources :user_bills, only: [:index, :show]
  end

  namespace :admin do |admin|

    get 'roles/tree_data/:type' => 'roles#tree_data'
    post 'roles/destroy_multi' => 'roles#destroy_multi'
    post 'users/destroy_multi' => 'users#destroy_multi'
    post 'permissions/destroy_multi' => 'permissions#destroy_multi'
    post 'organizations/destroy_multi' => 'organizations#destroy_multi'
    post 'code_tables/destroy_multi' => 'code_tables#destroy_multi'
    post 'attachments/destroy_multi' => 'attachments#destroy_multi'
    post 'customers/destroy_multi' => 'customers#destroy_multi'
    post 'classifications/destroy_multi' => 'classifications#destroy_multi'
    post 'commodities/destroy_multi' => 'commodities#destroy_multi'
    post 'communities/destroy_multi' => 'communities#destroy_multi'
    post 'shops/destroy_multi' => 'shops#destroy_multi'
    post 'employees/destroy_multi' => 'employees#destroy_multi'
    post 'orders/destroy_multi' => 'orders#destroy_multi'
    post 'order_infos/destroy_multi' => 'order_infos#destroy_multi'
    post 'manage_orders/destroy_multi' => 'manage_orders#destroy_multi'
    post 'order_comments/destroy_multi' => 'order_comments#destroy_multi'
    post 'shop_commodities/destroy_multi' => 'shop_commodities#destroy_multi'
    post 'shop_manage_users/destroy_multi' => 'shop_manage_users#destroy_multi'
    post 'express_orders/destroy_multi' => 'express_orders#destroy_multi'
    post 'notices/destroy_multi' => 'notices#destroy_multi'
    post 'adverts/destroy_multi' => 'adverts#destroy_multi'

    resources :dummy_shop_orders
    resources :shop_manage_users
    namespace :shop_statistics do
      get :index
      post :shop_total
      post :shop_all_total
      post :get_data
      post :hot_shipping_total
      post :hot_shipping_single
      post :express_num_total
    end
    resources :cancel_orders do |c|
      collection do
        get :index
        get :new
        post :get_shipping
        post :save_info
      end
    end
    resources :manage_orders do |c|
      collection do
        get :read_order_count, format: 'json'
        post :add_express_seller
      end
    end
    resources :order_infos do |c|
      collection do

      end
    end
    resources :roles
    resources :attachments
    resources :code_tables
    resources :organizations
    resources :permissions
    resources :customers
    resources :classifications

    get 'commodities/upload' => 'commodities#upload'
    post 'commodities/upload' => 'commodities#upload'
    resources :commodities
    resources :communities
    resources :shops
    resources :shop_commodities do
      collection do
        get :set_has_long
        get :change_left_count
      end
    end
    resources :order_comments
    resources :employees
    resources :orders
    resources :users do
      collection do
        get 'validate_user'
        get 'update_password'
        patch 'update_password'
      end
    end

    resources :express_orders do
      collection do
        get 'read_express_count'
      end
    end
    resources :adverts
    resources :notices
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  enum data_type: {normal: 0}

  belongs_to :author, class_name: 'User'
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/admin/attachments_controller.rb
# coding: UTF-8
class Admin::AttachmentsController < Admin::BaseController

  before_action :base_breadcrumb
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_action :name_breadcrumb_handler, only: [:show, :edit]
  before_action :action_common_breadcurmb, only: [:new, :edit]

  # GET /admin/attachments
  def index
    @attachments = initialize_grid(Attachment, page: params[:page], order: :created_at, order_direction: :desc)
  end

  # GET /admin/attachments/1
  def show
  end


  # GET /admin/attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /admin/attachments/1/edit
  def edit
  end

  # POST /admin/attachments
  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.author_id = current_user.id

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to admin_attachment_path(@attachment.id), notice: create_success_notice(:attachment) }
       format.json { render action: 'show', status: :created, location: @attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/attachments/1
  def update
    respond_to do |format|
      if @attachment.update_attributes(attachment_params)
       format.html { redirect_to admin_attachment_path(@attachment.id), notice: update_success_notice(:attachment) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/attachments/1
  def destroy
    begin
      @attachment.destroy
    rescue
      @attachment.update_attributes(enable: false)
    end

    respond_to do |format|
      format.html { redirect_to admin_attachments_path, notice: destroy_success_notice(:attachment) }
      format.json { head :no_content }
    end
  end

  def destroy_multi
    ids =params[:grid][:select_ids]
    if ids and ids.instance_of? Array
      ids.each do |id|
        attachment = Attachment.find(id)
        begin
          attachment.destroy! if attachment
        rescue ActiveRecord::RecordNotDestroyed
          attachment.update_attributes(enable: false)
          next
        end
      end
    end
  rescue
    flash[:notice] ="#{t 'common.delete_multi'}#{t 'common.fault'}"
    redirect_to action: 'index'
  else
    flash[:notice] ="#{t 'common.delete_multi'}#{t 'common.success'}"
    redirect_to action: 'index'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_attachment
    if params[:action] == 'show'
       @attachment = Attachment.find(params[:id])
    else
      @attachment = Attachment.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attachment_params

    params.require(:attachment).permit(:name, :avatar, :author_id, :position, :date_type)

  end

  def base_breadcrumb
    add_breadcrumb (t 'activerecord.attributes.attachment.admin_title'), admin_attachments_path
  end

  # add name breadcrumb with :show, :edit
  def name_breadcrumb_handler
    add_breadcrumb @attachment.name, admin_attachment_path(@attachment.id), class: :pjax
  end
end

app/helpers/admin/attachments_helper.rb
module Admin::AttachmentsHelper
end

app/views/admin/attachments/_form.html.erb
<%= simple_form_for([:admin, @attachment], html: {class: 'form-horizontal form-show',id: 'attachment_form' }) do |f| %>
<%= f.error_notification %>


  <%= f.input :name, autofocus: true %>

  <%= f.input :avatar, hint: '建议使用英文文件名' %>

  <%= f.input :position %>

  <%= f.input :data_type, collection: [['默认', 0]], include_blank: false %>


<div class="clearfix form-actions">
  <div class="col-md-offset-3 col-md-9">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

<script>
    $(function () {
        $('#attachment_form').validator_b3({
            errorElement: 'div',
            errorClass: 'help-block',
            focusInvalid: false,
            rules: {
            },
            messages: {
            }
        });


        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="attachment_list"]').addClass('active');
    } );
</script>

app/views/admin/attachments/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :edit, model_nav_name: :admin_attachment, pjax: true} %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/attachments/index.html.erb
<div class="row">
  <div class="col-xs-12">

    <%= render partial:  'common/nav', locals: {show_tab: :index, model_nav_name: :admin_attachment, pjax: true} %>

    <%= form_for 'Attachment', url: admin_attachments_destroy_multi_path, method: :post, data: { confirm: "#{  t 'common.confirm_delete'}"} do %>
    <button class="btn btn-minier btn-danger" type="submit"><i class="icon-trash"></i> <%= t 'common.delete_multi' %></button>
    <div id="admin_attachments">
      <%= grid(@attachments, show_filters: :when_filtered) do |g|
      g.action_column param_name: :select_ids, object_property: :id
      g.column name: "#{t 'activerecord.attributes.defaults.id'}", attribute: 'id', filter: false, ordering: true


      g.column name: "#{t 'activerecord.attributes.attachment.name'}", attribute: 'name' do |c|
        link_to c.name, admin_attachment_path(c.id), class: :pjax
      end

      g.column name: "#{t 'activerecord.attributes.attachment.author'}", attribute: 'author_id' do |c|
        c.author.name if c.author.present?
      end

      g.column name: "#{t 'activerecord.attributes.attachment.position'}", attribute: 'position'

      g.column name: "#{t 'activerecord.attributes.attachment.data_type'}", attribute: 'data_type'

        g.column  do |c|
          grid_operator(:admin_attachment_path, c.id)
        end
      end %>
    </div>

    <% end %>
  </div>
</div>

<script>
    $(function () {
        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="attachment_list"]').addClass('active');
    } );
</script>

app/views/admin/attachments/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :new, model_nav_name: :admin_attachment, pjax: true} %>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/attachments/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial: 'common/nav', locals: {show_tab: :show, model_nav_name: :admin_attachment, pjax: true} %>
    <div class="form-horizontal form-show" id="admin_attachment">

          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.attachment.name' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">

                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @attachment.name %>">

              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.attachment.avatar' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">

                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @attachment.avatar %>">

              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.attachment.author' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">

                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @attachment.author.name if @attachment.author.present? %>">

              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.attachment.position' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">

                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @attachment.position %>">

              </div>
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-xs-12 col-sm-3"><%= t 'activerecord.attributes.attachment.data_type' %></label>
            <div class="col-xs-12 col-sm-9">
              <div class="clearfix">

                    <input type="text" readonly="readonly" class="col-xs-12 col-sm-6" value="<%= @attachment.data_type %>">

              </div>
            </div>
          </div>

    </div>
  </div>
</div>
<script>
    $(function () {
        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="attachment_list"]').addClass('active');
    } );
</script>