config/routes.rb
Scaffold::Application.routes.draw do
  namespace :front do
    get 'portal/index'
  end

  devise_for :users, skip: [:registrations], controllers: {sessions: 'common/sessions'}

  root 'portal#index'
  get 'shop' => 'front/homes#home'
  get 'admin' => 'admin/users#index'

  get 'free_express' => 'portal#free_express'
  get 'get_addr/:id' => 'portal#get_addr'
  get 'notice/:id' => 'portal#notice'
  post 'save_addr' => 'portal#save_addr'

  namespace :front do |front|
    namespace :homes do
      get :pay_view
      post :pay_call_back
      get :express
      get :home_index, format: 'json'
      get :get_classification
      get :get_shop
      get :get_region_shop
      get :shipping_address
      get :shipping_address_default
      get :get_order_old
      get :get_order_ing
      get :get_order_detail
      get :get_score_detail
      get :get_person_info
      post :commentary_order
      post :shipping_address_change
      post :shipping_address_new
      post :order_new
      get :cancel_order_customer
      post :express_entrue
      post :pay_online
      post :change_person_info
      post :search_shipping_info
    end
    resources :contacts do
      collection do
        get :upload
        post :upload_file
        get :tree_data, format: 'json'
      end
    end

    get 'users/edit' => 'users#edit'
    patch 'users/update' => 'users#update'
    get 'users/update_password' => 'users#update_password'
    patch 'users/update_password' => 'users#update_password'
    resources :user_bills, only: [:index, :show]
  end

  namespace :admin do |admin|

    get 'roles/tree_data/:type' => 'roles#tree_data'
    post 'roles/destroy_multi' => 'roles#destroy_multi'
    post 'users/destroy_multi' => 'users#destroy_multi'
    post 'permissions/destroy_multi' => 'permissions#destroy_multi'
    post 'organizations/destroy_multi' => 'organizations#destroy_multi'
    post 'code_tables/destroy_multi' => 'code_tables#destroy_multi'
    post 'attachments/destroy_multi' => 'attachments#destroy_multi'
    post 'customers/destroy_multi' => 'customers#destroy_multi'
    post 'classifications/destroy_multi' => 'classifications#destroy_multi'
    post 'commodities/destroy_multi' => 'commodities#destroy_multi'
    post 'communities/destroy_multi' => 'communities#destroy_multi'
    post 'shops/destroy_multi' => 'shops#destroy_multi'
    post 'employees/destroy_multi' => 'employees#destroy_multi'
    post 'orders/destroy_multi' => 'orders#destroy_multi'
    post 'order_infos/destroy_multi' => 'order_infos#destroy_multi'
    post 'manage_orders/destroy_multi' => 'manage_orders#destroy_multi'
    post 'order_comments/destroy_multi' => 'order_comments#destroy_multi'
    post 'shop_commodities/destroy_multi' => 'shop_commodities#destroy_multi'
    post 'shop_manage_users/destroy_multi' => 'shop_manage_users#destroy_multi'
    post 'express_orders/destroy_multi' => 'express_orders#destroy_multi'
    post 'notices/destroy_multi' => 'notices#destroy_multi'
    post 'adverts/destroy_multi' => 'adverts#destroy_multi'

    resources :dummy_shop_orders
    resources :shop_manage_users
    namespace :shop_statistics do
      get :index
      post :shop_total
      post :shop_all_total
      post :get_data
      post :hot_shipping_total
      post :hot_shipping_single
      post :express_num_total
    end
    resources :cancel_orders do |c|
      collection do
        get :index
        get :new
        post :get_shipping
        post :save_info
      end
    end
    resources :manage_orders do |c|
      collection do
        get :read_order_count, format: 'json'
        post :add_express_seller
      end
    end
    resources :order_infos do |c|
      collection do

      end
    end
    resources :roles
    resources :attachments
    resources :code_tables
    resources :organizations
    resources :permissions
    resources :customers
    resources :classifications

    get 'commodities/upload' => 'commodities#upload'
    post 'commodities/upload' => 'commodities#upload'
    resources :commodities
    resources :communities
    resources :shops
    resources :shop_commodities do
      collection do
        get :set_has_long
        get :change_left_count
      end
    end
    resources :order_comments
    resources :employees
    resources :orders
    resources :users do
      collection do
        get 'validate_user'
        get 'update_password'
        patch 'update_password'
      end
    end

    resources :express_orders do
      collection do
        get 'read_express_count'
      end
    end
    resources :adverts
    resources :notices
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :score_records
  belongs_to :customer, class_name: 'Customer'
  belongs_to :shop, class_name: 'Shop'
  has_many :order_details
  has_one :order_express
  has_many :order_logs
  has_many :order_details
  has_many :dummy_shop_orders
end

app/controllers/admin/orders_controller.rb
# coding: UTF-8
class Admin::OrdersController < Admin::BaseController
  load_and_authorize_resource
  before_action :base_breadcrumb
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :name_breadcrumb_handler, only: [:show, :edit]
  before_action :action_common_breadcurmb, only: [:new, :edit]
  # GET /admin/orders
  def index
    if !current_user.permissions.find_by(subject: 'all').present?
      @orders = initialize_grid(Order.where(shop_id: current_user.shop_manage_id).accessible_by(current_ability, :manage), page: params[:page], order: :created_at, order_direction: :desc)
    else
      @orders = initialize_grid(Order.accessible_by(current_ability, :manage), page: params[:page], order: :created_at, order_direction: :desc)
    end
    @status_option = ['用户下单','等待支付','等待确认','等待配送','配送中', '待评价', '已评价']
  end



  private
  def base_breadcrumb
    add_breadcrumb (t 'activerecord.attributes.order.admin_title'), admin_orders_path
  end

  # add name breadcrumb with :show, :edit
  def name_breadcrumb_handler
    add_breadcrumb '订单信息', admin_order_path(@order.id), class: :pjax
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= render partial:  'common/nav', locals: {show_tab: :index, model_nav_name: :admin_order, pjax: true, model: 'Order'} %>
    <%= form_for 'Order', url: admin_orders_destroy_multi_path, method: :post, data: { confirm: "#{  t 'common.confirm_delete'}"} do %>
    <div id="admin_orders">
      <%= grid(@orders, show_filters: :when_filtered) do |g|
      g.action_column param_name: :select_ids, object_property: :id
      g.column name: "#{t 'activerecord.attributes.defaults.id'}", attribute: 'id', filter: false, ordering: true
      g.column name: "#{t 'activerecord.attributes.order.custom'}", attribute: 'customer_id' do |c|
        c.customer.name  if c.customer.present?
      end
      # g.column name: "#{t 'activerecord.attributes.order.shop'}", attribute: 'shop_id' do |c|
      #   c.shop.name if c.shop.present?
      # end
      g.column name: "#{t 'activerecord.attributes.order.commodity_amount'}", attribute: 'commodity_amount'

      g.column name: '准备耗时' do |c|
        ''+((c.set_out_at - c.created_at)/60).to_i.to_s + '分' if(c.set_out_at.present?)
      end

      g.column name: '派送耗时' do |c|
        ''+((c.order_express.complete_date - c.order_express.express_start_time)/60).to_i.to_s + '分'  if c.order_express.present? &&  (c.order_express.complete_date.present? && c.order_express.express_start_time.present?)
      end

      g.column name: '送货员姓名' do |c|
        c.order_express.user.name if c.order_express.present? && c.order_express.user.present?
      end
      g.column name: "#{t 'activerecord.attributes.order.status'}", attribute: 'status' do |c|
            "#{@status_option[c.status]}"
      end


        g.column  do |c|
          # grid_operator(:admin_order_path, c.id, Order)
        end
      end %>
    </div>

    <% end %>
  </div>
</div>

<script>
    $(function () {
        $('.nav.nav-list li.active').removeClass('active');
        $('.nav.nav-list li[data-model="order_list"]').addClass('active');
    } );
</script>